import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Topbar from '@/components/topbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <main className="bg-gray-100 h-screen flex items-center justify-center">
          <div className="h-[95vh] w-[95vw] bg-white p-8 rounded-lg shadow-lg">
            <Topbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
